name: Empty Commit

on: workflow_dispatch

jobs:
  make_empty_commit:
    name: Make Empty Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set commit flags
        run: |
          git config commit.gpgsign false
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@example.com"
      - name: Create commit
        run: git commit --allow-empty --no-verify -m "Empty commit"
      - name: Push commit
        run: git push
